/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.demo.iot.demux1to4;

import hu.bme.mit.gamma.demo.iot.IStatemachine;

public interface IDeMux1to4Statemachine extends IStatemachine {
	public interface SCIIn {
	
		public void raiseNewData(long value);
		
	}
	
	public SCIIn getSCIIn();
	
	public interface SCIOut1 {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIOut1 getSCIOut1();
	
	public interface SCIOut2 {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIOut2 getSCIOut2();
	
	public interface SCIOut3 {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIOut3 getSCIOut3();
	
	public interface SCIOut4 {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIOut4 getSCIOut4();
	
}
