/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.casestudy.iotcamera1.smartcontrol;

import hu.bme.mit.gamma.casestudy.iotcamera1.IStatemachine;
import java.util.List;

public interface ISmartControlStatemachine extends IStatemachine {
	public interface SCIStatus {
	
		public void raiseFull();
		
		public void raiseFree();
		
	}
	
	public SCIStatus getSCIStatus();
	
	public interface SCIInPicStream {
	
		public void raiseNewData();
		
	}
	
	public SCIInPicStream getSCIInPicStream();
	
	public interface SCINetworkStream {
	
		public boolean isRaisedNewData();
		
	public List<SCINetworkStreamListener> getListeners();
	}
	
	public interface SCINetworkStreamListener {
	
		public void onNewDataRaised();
		}
	
	public SCINetworkStream getSCINetworkStream();
	
	public interface SCILocalStream {
	
		public boolean isRaisedNewData();
		
	public List<SCILocalStreamListener> getListeners();
	}
	
	public interface SCILocalStreamListener {
	
		public void onNewDataRaised();
		}
	
	public SCILocalStream getSCILocalStream();
	
}
