apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt-broker
  name: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt-broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: mqtt-broker
    spec:
      containers:
        - image: eclipse-mosquitto
          name: mqtt-broker
          ports:
            - containerPort: 1883
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /mosquitto/config/mosquitto.conf
              name: mqtt-broker-claim0
      restartPolicy: Always
      volumes:
        - name: mqtt-broker-claim0
          persistentVolumeClaim:
            claimName: mqtt-broker-claim0
status: {}
