/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.demo.iot.sink4to1;

import hu.bme.mit.gamma.demo.iot.IStatemachine;

public interface ISink4To1Statemachine extends IStatemachine {
	public interface SCIIn1 {
	
		public void raiseNewData();
		
	}
	
	public SCIIn1 getSCIIn1();
	
	public interface SCIIn2 {
	
		public void raiseNewData();
		
	}
	
	public SCIIn2 getSCIIn2();
	
	public interface SCIIn3 {
	
		public void raiseNewData();
		
	}
	
	public SCIIn3 getSCIIn3();
	
	public interface SCIIn4 {
	
		public void raiseNewData();
		
	}
	
	public SCIIn4 getSCIIn4();
	
	public interface SCIOut {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIOut getSCIOut();
	
}
