/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.casestudy.iotcamera1.lpdetqueuemanager;

import hu.bme.mit.gamma.casestudy.iotcamera1.IStatemachine;
import java.util.List;

public interface ILPDetQueueManagerStatemachine extends IStatemachine {
	public interface SCITraffic {
	
		public void raiseNewCar();
		
	}
	
	public SCITraffic getSCITraffic();
	
	public interface SCIPreProcessedImg {
	
		public void raiseNewData();
		
	}
	
	public SCIPreProcessedImg getSCIPreProcessedImg();
	
	public interface SCIImg {
	
		public boolean isRaisedNewData();
		
	public List<SCIImgListener> getListeners();
	}
	
	public interface SCIImgListener {
	
		public void onNewDataRaised();
		}
	
	public SCIImg getSCIImg();
	
	public interface SCIStatus {
	
		public boolean isRaisedFull();
		
		public boolean isRaisedFree();
		
	public List<SCIStatusListener> getListeners();
	}
	
	public interface SCIStatusListener {
	
		public void onFullRaised();
		public void onFreeRaised();
		}
	
	public SCIStatus getSCIStatus();
	
}
