/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.casestudy.camea.queuemanager;

import hu.bme.mit.gamma.casestudy.camea.IStatemachine;

public interface IQueueManagerStatemachine extends IStatemachine {
	public interface SCIInStream {
	
		public void raiseNewData();
		
	}
	
	public SCIInStream getSCIInStream();
	
	public interface SCIOutStream {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIOutStream getSCIOutStream();
	
	public interface SCIDataLoss {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIDataLoss getSCIDataLoss();
	
	public interface SCIToHW {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIToHW getSCIToHW();
	
	public interface SCIFromHW {
	
		public void raiseNewData();
		
	}
	
	public SCIFromHW getSCIFromHW();
	
}
