#!/bin/bash
docker run -p 8086:8086 \
      -e DOCKER_INFLUXDB_INIT_USERNAME=admin \
      -e DOCKER_INFLUXDB_INIT_PASSWORD=LaborImage \
      -e DOCKER_INFLUXDB_INIT_ORG=ftsrg \
      -e DOCKER_INFLUXDB_INIT_BUCKET=main-bucket \
      --name influxdb2 \
      influxdb:2.0.7