FROM python:3

WORKDIR /usr/src/app


RUN pip install pytesseract
RUN pip install easyocr
RUN pip install rticonnextdds_connector
RUN pip install opencv-python
RUN pip install numpy
RUN pip install influxdb
RUN pip install paho-mqtt