/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.casestudy.camea.basictraffic;

import hu.bme.mit.gamma.casestudy.camea.IStatemachine;

public interface IBasicTrafficStatemachine extends IStatemachine {
	public interface SCIInPort {
	
		public void raiseNewCar();
		
	}
	
	public SCIInPort getSCIInPort();
	
	public interface SCIOutPort {
	
		public boolean isRaisedNewData();
		
	}
	
	public SCIOutPort getSCIOutPort();
	
}
