/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.usecase.epas.sensor;

import hu.bme.mit.gamma.usecase.epas.IStatemachine;
import java.util.List;

public interface ISensorStatemachine extends IStatemachine {
	public interface SCIHWFault {
	
		public void raiseDet();
		
		public void raiseLatent();
		
	}
	
	public SCIHWFault getSCIHWFault();
	
	public interface SCISensorFault {
	
		public boolean isRaisedDet();
		
		public boolean isRaisedLatent();
		
	public List<SCISensorFaultListener> getListeners();
	}
	
	public interface SCISensorFaultListener {
	
		public void onDetRaised();
		public void onLatentRaised();
		}
	
	public SCISensorFault getSCISensorFault();
	
}
