/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.usecase.epas.sensor;

import java.util.LinkedList;
import java.util.List;

public class SensorStatemachine implements ISensorStatemachine {
	protected class SCIHWFaultImpl implements SCIHWFault {
	
		private boolean det;
		
		
		public void raiseDet() {
			det = true;
		}
		
		private boolean latent;
		
		
		public void raiseLatent() {
			latent = true;
		}
		
		protected void clearEvents() {
			det = false;
			latent = false;
		}
	}
	
	
	protected class SCISensorFaultImpl implements SCISensorFault {
	
		private List<SCISensorFaultListener> listeners = new LinkedList<SCISensorFaultListener>();
		
		public List<SCISensorFaultListener> getListeners() {
			return listeners;
		}
		private boolean det;
		
		
		public boolean isRaisedDet() {
			return det;
		}
		
		protected void raiseDet() {
			det = true;
			for (SCISensorFaultListener listener : listeners) {
				listener.onDetRaised();
			}
		}
		
		private boolean latent;
		
		
		public boolean isRaisedLatent() {
			return latent;
		}
		
		protected void raiseLatent() {
			latent = true;
			for (SCISensorFaultListener listener : listeners) {
				listener.onLatentRaised();
			}
		}
		
		protected void clearEvents() {
		}
		protected void clearOutEvents() {
		
		det = false;
		latent = false;
		}
		
	}
	
	
	protected SCIHWFaultImpl sCIHWFault;
	
	protected SCISensorFaultImpl sCISensorFault;
	
	private boolean initialized = false;
	
	public enum State {
		sensor_Ok,
		sensor_Off,
		sensor_LatentFailure,
		$NullState$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	public SensorStatemachine() {
		sCIHWFault = new SCIHWFaultImpl();
		sCISensorFault = new SCISensorFaultImpl();
	}
	
	public void init() {
		this.initialized = true;
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		enterSequence_Sensor_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case sensor_Ok:
				sensor_Ok_react(true);
				break;
			case sensor_Off:
				sensor_Off_react(true);
				break;
			case sensor_LatentFailure:
				sensor_LatentFailure_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence_Sensor();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCIHWFault.clearEvents();
		sCISensorFault.clearEvents();
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCISensorFault.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case sensor_Ok:
			return stateVector[0] == State.sensor_Ok;
		case sensor_Off:
			return stateVector[0] == State.sensor_Off;
		case sensor_LatentFailure:
			return stateVector[0] == State.sensor_LatentFailure;
		default:
			return false;
		}
	}
	
	public SCIHWFault getSCIHWFault() {
		return sCIHWFault;
	}
	
	public SCISensorFault getSCISensorFault() {
		return sCISensorFault;
	}
	
	/* Entry action for state 'Off'. */
	private void entryAction_Sensor_Off() {
		sCISensorFault.raiseDet();
	}
	
	/* Entry action for state 'LatentFailure'. */
	private void entryAction_Sensor_LatentFailure() {
		sCISensorFault.raiseLatent();
	}
	
	/* 'default' enter sequence for state Ok */
	private void enterSequence_Sensor_Ok_default() {
		nextStateIndex = 0;
		stateVector[0] = State.sensor_Ok;
	}
	
	/* 'default' enter sequence for state Off */
	private void enterSequence_Sensor_Off_default() {
		entryAction_Sensor_Off();
		nextStateIndex = 0;
		stateVector[0] = State.sensor_Off;
	}
	
	/* 'default' enter sequence for state LatentFailure */
	private void enterSequence_Sensor_LatentFailure_default() {
		entryAction_Sensor_LatentFailure();
		nextStateIndex = 0;
		stateVector[0] = State.sensor_LatentFailure;
	}
	
	/* 'default' enter sequence for region Sensor */
	private void enterSequence_Sensor_default() {
		react_Sensor__entry_Default();
	}
	
	/* Default exit sequence for state Ok */
	private void exitSequence_Sensor_Ok() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Off */
	private void exitSequence_Sensor_Off() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state LatentFailure */
	private void exitSequence_Sensor_LatentFailure() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region Sensor */
	private void exitSequence_Sensor() {
		switch (stateVector[0]) {
		case sensor_Ok:
			exitSequence_Sensor_Ok();
			break;
		case sensor_Off:
			exitSequence_Sensor_Off();
			break;
		case sensor_LatentFailure:
			exitSequence_Sensor_LatentFailure();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Sensor__entry_Default() {
		enterSequence_Sensor_Ok_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean sensor_Ok_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCIHWFault.det) {
					exitSequence_Sensor_Ok();
					enterSequence_Sensor_Off_default();
				} else {
					if (sCIHWFault.latent) {
						exitSequence_Sensor_Ok();
						enterSequence_Sensor_LatentFailure_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean sensor_Off_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean sensor_LatentFailure_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
}
