/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.usecase.epas.mainctrl;

import hu.bme.mit.gamma.usecase.epas.IStatemachine;
import java.util.List;

public interface IMainctrlStatemachine extends IStatemachine {
	public interface SCIMonitor {
	
		public boolean isRaisedWarning();
		
		public boolean isRaisedSelfsteering();
		
		public boolean isRaisedLoa();
		
	public List<SCIMonitorListener> getListeners();
	}
	
	public interface SCIMonitorListener {
	
		public void onWarningRaised();
		public void onSelfsteeringRaised();
		public void onLoaRaised();
		}
	
	public SCIMonitor getSCIMonitor();
	
	public interface SCIS1HW {
	
		public void raiseDet();
		
		public void raiseLatent();
		
	}
	
	public SCIS1HW getSCIS1HW();
	
	public interface SCIS2HW {
	
		public void raiseDet();
		
		public void raiseLatent();
		
	}
	
	public SCIS2HW getSCIS2HW();
	
	public interface SCIS3HW {
	
		public void raiseDet();
		
		public void raiseLatent();
		
	}
	
	public SCIS3HW getSCIS3HW();
	
	public interface SCIUCHW {
	
		public void raiseShutdown();
		
	}
	
	public SCIUCHW getSCIUCHW();
	
}
