/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef SENSOR_H_
#define SENSOR_H_


#include "sc_types.h"
#include "StatemachineInterface.h"

/*! \file Header of the state machine 'Sensor'.
*/


/*! Define indices of states in the StateConfVector */
#define SCVI_SENSOR_OK 0
#define SCVI_SENSOR_OFF 0
#define SCVI_SENSOR_LATENTFAILURE 0


class Sensor : public StatemachineInterface
{
	public:
		Sensor();
		
		virtual ~Sensor();
		
		/*! Enumeration of all states */ 
		typedef enum
		{
			Sensor_last_state,
			Sensor_Ok,
			Sensor_Off,
			Sensor_LatentFailure
		} SensorStates;
					
		static const sc_integer numStates = 3;
		
		//! Inner class for HWFault interface scope.
		class SCI_HWFault
		{
			public:
				/*! Raises the in event 'det' that is defined in the interface scope 'HWFault'. */
				void raise_det();
				
				
				/*! Raises the in event 'latent' that is defined in the interface scope 'HWFault'. */
				void raise_latent();
				
				
				
			private:
				friend class Sensor;
				sc_boolean det_raised;
				sc_boolean latent_raised;
				
				
		};
		
		/*! Returns an instance of the interface class 'SCI_HWFault'. */
		SCI_HWFault* getSCI_HWFault();
		
		//! Inner class for SensorFault interface scope.
		class SCI_SensorFault
		{
			public:
				/*! Checks if the out event 'det' that is defined in the interface scope 'SensorFault' has been raised. */
				sc_boolean isRaised_det() const;
				
				
				/*! Checks if the out event 'latent' that is defined in the interface scope 'SensorFault' has been raised. */
				sc_boolean isRaised_latent() const;
				
				
				
			private:
				friend class Sensor;
				sc_boolean det_raised;
				sc_boolean latent_raised;
				
				
		};
		
		/*! Returns an instance of the interface class 'SCI_SensorFault'. */
		SCI_SensorFault* getSCI_SensorFault();
		
		
		/*
		 * Functions inherited from StatemachineInterface
		 */
		virtual void init();
		
		virtual void enter();
		
		virtual void exit();
		
		virtual void runCycle();
		
		/*!
		* Checks if the state machine is active (until 2.4.1 this method was used for states).
		* A state machine is active if it has been entered. It is inactive if it has not been entered at all or if it has been exited.
		*/
		virtual sc_boolean isActive() const;
		
		
		/*!
		* Checks if all active states are final. 
		* If there are no active states then the state machine is considered being inactive. In this case this method returns false.
		*/
		virtual sc_boolean isFinal() const;
		
		
		/*! Checks if the specified state is active (until 2.4.1 the used method for states was calles isActive()). */
		sc_boolean isStateActive(SensorStates state) const;
		
		
		
	protected:
		
		
	private:
		
		
		//! the maximum number of orthogonal states defines the dimension of the state configuration vector.
		static const sc_ushort maxOrthogonalStates = 1;
		
		
		
		SensorStates stateConfVector[maxOrthogonalStates];
		
		sc_ushort stateConfVectorPosition;
		
		SCI_HWFault ifaceHWFault;
		SCI_SensorFault ifaceSensorFault;
		
		// prototypes of all internal functions
		
		void enact_Sensor_Off();
		void enact_Sensor_LatentFailure();
		void enseq_Sensor_Ok_default();
		void enseq_Sensor_Off_default();
		void enseq_Sensor_LatentFailure_default();
		void enseq_Sensor_default();
		void exseq_Sensor_Ok();
		void exseq_Sensor_Off();
		void exseq_Sensor_LatentFailure();
		void exseq_Sensor();
		void react_Sensor__entry_Default();
		sc_boolean react();
		sc_boolean Sensor_Ok_react(const sc_boolean try_transition);
		sc_boolean Sensor_Off_react(const sc_boolean try_transition);
		sc_boolean Sensor_LatentFailure_react(const sc_boolean try_transition);
		void clearInEvents();
		void clearOutEvents();
		
		
		
		
};




#endif /* SENSOR_H_ */
