/** Generated by YAKINDU Statechart Tools code generator. */

#include "DeMux1to4.h"
#include "../src/sc_types.h"

/*! \file Implementation of the state machine 'DeMux1to4'
*/

#define SC_UNUSED(P) (void)(P)
/* prototypes of all internal functions */
static sc_boolean check_main_region__choice_0_tr0_tr0(const DeMux1to4* handle);
static sc_boolean check_main_region__choice_0_tr1_tr1(const DeMux1to4* handle);
static sc_boolean check_main_region__choice_0_tr2_tr2(const DeMux1to4* handle);
static sc_boolean check_main_region__choice_0_tr3_tr3(const DeMux1to4* handle);
static void effect_main_region__choice_0_tr0(DeMux1to4* handle);
static void effect_main_region__choice_0_tr1(DeMux1to4* handle);
static void effect_main_region__choice_0_tr2(DeMux1to4* handle);
static void effect_main_region__choice_0_tr3(DeMux1to4* handle);
static void effect_main_region__choice_0_tr4(DeMux1to4* handle);
static void enseq_main_region_StateA_default(DeMux1to4* handle);
static void enseq_main_region_default(DeMux1to4* handle);
static void exseq_main_region_StateA(DeMux1to4* handle);
static void exseq_main_region(DeMux1to4* handle);
static void react_main_region__choice_0(DeMux1to4* handle);
static void react_main_region__entry_Default(DeMux1to4* handle);
static sc_boolean react(DeMux1to4* handle);
static sc_boolean main_region_StateA_react(DeMux1to4* handle, const sc_boolean try_transition);
static void clearInEvents(DeMux1to4* handle);
static void clearOutEvents(DeMux1to4* handle);


void deMux1to4_init(DeMux1to4* handle)
{
	sc_integer i;
	
	for (i = 0; i < DEMUX1TO4_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = DeMux1to4_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
	/* Default init sequence for statechart DeMux1to4 */
	handle->internal.sel = 0;
}

void deMux1to4_enter(DeMux1to4* handle)
{
	/* Default enter sequence for statechart DeMux1to4 */
	enseq_main_region_default(handle);
}

void deMux1to4_runCycle(DeMux1to4* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < DEMUX1TO4_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case DeMux1to4_main_region_StateA:
		{
			main_region_StateA_react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void deMux1to4_exit(DeMux1to4* handle)
{
	/* Default exit sequence for statechart DeMux1to4 */
	exseq_main_region(handle);
}

sc_boolean deMux1to4_isActive(const DeMux1to4* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < DEMUX1TO4_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != DeMux1to4_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean deMux1to4_isFinal(const DeMux1to4* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean deMux1to4_isStateActive(const DeMux1to4* handle, DeMux1to4States state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case DeMux1to4_main_region_StateA :
			result = (sc_boolean) (handle->stateConfVector[SCVI_DEMUX1TO4_MAIN_REGION_STATEA] == DeMux1to4_main_region_StateA
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(DeMux1to4* handle)
{
	handle->ifaceIn.NewEvent_raised = bool_false;
}

static void clearOutEvents(DeMux1to4* handle)
{
	handle->ifaceOut1.NewEvent_raised = bool_false;
	handle->ifaceOut2.NewEvent_raised = bool_false;
	handle->ifaceOut3.NewEvent_raised = bool_false;
	handle->ifaceOut4.NewEvent_raised = bool_false;
}

void deMux1to4IfaceIn_raise_newEvent(DeMux1to4* handle, sc_integer value)
{
	handle->ifaceIn.NewEvent_value = value;
	handle->ifaceIn.NewEvent_raised = bool_true;
}



sc_boolean deMux1to4IfaceOut1_israised_newEvent(const DeMux1to4* handle)
{
	return handle->ifaceOut1.NewEvent_raised;
}


sc_boolean deMux1to4IfaceOut2_israised_newEvent(const DeMux1to4* handle)
{
	return handle->ifaceOut2.NewEvent_raised;
}


sc_boolean deMux1to4IfaceOut3_israised_newEvent(const DeMux1to4* handle)
{
	return handle->ifaceOut3.NewEvent_raised;
}


sc_boolean deMux1to4IfaceOut4_israised_newEvent(const DeMux1to4* handle)
{
	return handle->ifaceOut4.NewEvent_raised;
}


/* implementations of all internal functions */

static sc_boolean check_main_region__choice_0_tr0_tr0(const DeMux1to4* handle)
{
	return (handle->internal.sel) == (1);
}

static sc_boolean check_main_region__choice_0_tr1_tr1(const DeMux1to4* handle)
{
	return (handle->internal.sel) == (2);
}

static sc_boolean check_main_region__choice_0_tr2_tr2(const DeMux1to4* handle)
{
	return (handle->internal.sel) == (3);
}

static sc_boolean check_main_region__choice_0_tr3_tr3(const DeMux1to4* handle)
{
	return (handle->internal.sel) == (4);
}

static void effect_main_region__choice_0_tr0(DeMux1to4* handle)
{
	handle->ifaceOut1.NewEvent_raised = bool_true;
	enseq_main_region_StateA_default(handle);
}

static void effect_main_region__choice_0_tr1(DeMux1to4* handle)
{
	handle->ifaceOut2.NewEvent_raised = bool_true;
	enseq_main_region_StateA_default(handle);
}

static void effect_main_region__choice_0_tr2(DeMux1to4* handle)
{
	handle->ifaceOut3.NewEvent_raised = bool_true;
	enseq_main_region_StateA_default(handle);
}

static void effect_main_region__choice_0_tr3(DeMux1to4* handle)
{
	handle->ifaceOut4.NewEvent_raised = bool_true;
	enseq_main_region_StateA_default(handle);
}

static void effect_main_region__choice_0_tr4(DeMux1to4* handle)
{
	enseq_main_region_StateA_default(handle);
}

/* 'default' enter sequence for state StateA */
static void enseq_main_region_StateA_default(DeMux1to4* handle)
{
	/* 'default' enter sequence for state StateA */
	handle->stateConfVector[0] = DeMux1to4_main_region_StateA;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(DeMux1to4* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state StateA */
static void exseq_main_region_StateA(DeMux1to4* handle)
{
	/* Default exit sequence for state StateA */
	handle->stateConfVector[0] = DeMux1to4_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(DeMux1to4* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of DeMux1to4.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case DeMux1to4_main_region_StateA :
		{
			exseq_main_region_StateA(handle);
			break;
		}
		default: break;
	}
}

/* The reactions of state null. */
static void react_main_region__choice_0(DeMux1to4* handle)
{
	/* The reactions of state null. */
	if (check_main_region__choice_0_tr0_tr0(handle) == bool_true)
	{ 
		effect_main_region__choice_0_tr0(handle);
	}  else
	{
		if (check_main_region__choice_0_tr1_tr1(handle) == bool_true)
		{ 
			effect_main_region__choice_0_tr1(handle);
		}  else
		{
			if (check_main_region__choice_0_tr2_tr2(handle) == bool_true)
			{ 
				effect_main_region__choice_0_tr2(handle);
			}  else
			{
				if (check_main_region__choice_0_tr3_tr3(handle) == bool_true)
				{ 
					effect_main_region__choice_0_tr3(handle);
				}  else
				{
					effect_main_region__choice_0_tr4(handle);
				}
			}
		}
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(DeMux1to4* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_StateA_default(handle);
}

static sc_boolean react(DeMux1to4* handle) {
	SC_UNUSED(handle);
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean main_region_StateA_react(DeMux1to4* handle, const sc_boolean try_transition) {
	/* The reactions of state StateA. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->ifaceIn.NewEvent_raised == bool_true)
			{ 
				exseq_main_region_StateA(handle);
				handle->internal.sel = handle->ifaceIn.NewEvent_value;
				react_main_region__choice_0(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	return did_transition;
}


