/** Generated by YAKINDU Statechart Tools code generator. */

#include "Sink4To1.h"
#include "../src/sc_types.h"

/*! \file Implementation of the state machine 'Sink4To1'
*/

#define SC_UNUSED(P) (void)(P)
/* prototypes of all internal functions */
static void enseq_main_region_Main_default(Sink4To1* handle);
static void enseq_main_region_default(Sink4To1* handle);
static void exseq_main_region_Main(Sink4To1* handle);
static void exseq_main_region(Sink4To1* handle);
static void react_main_region__entry_Default(Sink4To1* handle);
static sc_boolean react(Sink4To1* handle);
static sc_boolean main_region_Main_react(Sink4To1* handle, const sc_boolean try_transition);
static void clearInEvents(Sink4To1* handle);
static void clearOutEvents(Sink4To1* handle);


void sink4To1_init(Sink4To1* handle)
{
	sc_integer i;
	
	for (i = 0; i < SINK4TO1_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Sink4To1_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
}

void sink4To1_enter(Sink4To1* handle)
{
	/* Default enter sequence for statechart Sink4To1 */
	enseq_main_region_default(handle);
}

void sink4To1_runCycle(Sink4To1* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < SINK4TO1_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case Sink4To1_main_region_Main:
		{
			main_region_Main_react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void sink4To1_exit(Sink4To1* handle)
{
	/* Default exit sequence for statechart Sink4To1 */
	exseq_main_region(handle);
}

sc_boolean sink4To1_isActive(const Sink4To1* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < SINK4TO1_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Sink4To1_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean sink4To1_isFinal(const Sink4To1* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean sink4To1_isStateActive(const Sink4To1* handle, Sink4To1States state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Sink4To1_main_region_Main :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SINK4TO1_MAIN_REGION_MAIN] == Sink4To1_main_region_Main
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Sink4To1* handle)
{
	handle->ifaceIn1.NewData_raised = bool_false;
	handle->ifaceIn2.NewData_raised = bool_false;
	handle->ifaceIn3.NewData_raised = bool_false;
	handle->ifaceIn4.NewData_raised = bool_false;
}

static void clearOutEvents(Sink4To1* handle)
{
	handle->ifaceOut.NewData_raised = bool_false;
}

void sink4To1IfaceIn1_raise_newData(Sink4To1* handle)
{
	handle->ifaceIn1.NewData_raised = bool_true;
}


void sink4To1IfaceIn2_raise_newData(Sink4To1* handle)
{
	handle->ifaceIn2.NewData_raised = bool_true;
}


void sink4To1IfaceIn3_raise_newData(Sink4To1* handle)
{
	handle->ifaceIn3.NewData_raised = bool_true;
}


void sink4To1IfaceIn4_raise_newData(Sink4To1* handle)
{
	handle->ifaceIn4.NewData_raised = bool_true;
}



sc_boolean sink4To1IfaceOut_israised_newData(const Sink4To1* handle)
{
	return handle->ifaceOut.NewData_raised;
}


/* implementations of all internal functions */

/* 'default' enter sequence for state Main */
static void enseq_main_region_Main_default(Sink4To1* handle)
{
	/* 'default' enter sequence for state Main */
	handle->stateConfVector[0] = Sink4To1_main_region_Main;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Sink4To1* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Main */
static void exseq_main_region_Main(Sink4To1* handle)
{
	/* Default exit sequence for state Main */
	handle->stateConfVector[0] = Sink4To1_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(Sink4To1* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Sink4To1.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Sink4To1_main_region_Main :
		{
			exseq_main_region_Main(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Sink4To1* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Main_default(handle);
}

static sc_boolean react(Sink4To1* handle) {
	SC_UNUSED(handle);
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean main_region_Main_react(Sink4To1* handle, const sc_boolean try_transition) {
	/* The reactions of state Main. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->ifaceIn1.NewData_raised == bool_true)
			{ 
				exseq_main_region_Main(handle);
				handle->ifaceOut.NewData_raised = bool_true;
				enseq_main_region_Main_default(handle);
			}  else
			{
				if (handle->ifaceIn2.NewData_raised == bool_true)
				{ 
					exseq_main_region_Main(handle);
					handle->ifaceOut.NewData_raised = bool_true;
					enseq_main_region_Main_default(handle);
				}  else
				{
					if (handle->ifaceIn3.NewData_raised == bool_true)
					{ 
						exseq_main_region_Main(handle);
						handle->ifaceOut.NewData_raised = bool_true;
						enseq_main_region_Main_default(handle);
					}  else
					{
						if (handle->ifaceIn3.NewData_raised == bool_true)
						{ 
							exseq_main_region_Main(handle);
							handle->ifaceOut.NewData_raised = bool_true;
							enseq_main_region_Main_default(handle);
						}  else
						{
							did_transition = bool_false;
						}
					}
				}
			}
		} 
	} 
	return did_transition;
}


